# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-jdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test with LTS releases
        jdk: [ 8, 11 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up OpenJDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'zulu'  # =openJDK
        cache: gradle
    - name: Set up elasticsearch
      run: docker compose up -d elasticsearch
    - name: Install python
      run: sudo apt-get install --assume-yes python3 python3-setuptools python3-pip 
    - name: Update pip
      run: pip3 install --upgrade pip
    - name: Install libraries via pip (xmltodict and wget)
      run: pip3 install xmltodict wget
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Ptravis clean check jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./build/reports/jacoco/test/jacocoTestReport.xml #optional
    - name: Shut down elasticsearch
      run: docker compose down
      